tasks:
  - name: Dependencies & Database
    init: |
      bash src/scripts/generateAwsExports.sh $ENDPOINT $API_KEY > src/aws-exports.js
      npm install
      npm run build
    command: |
      bash src/scripts/generateAwsExports.sh $ENDPOINT $API_KEY > src/aws-exports.js
      npm run start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - dbaeumer.vscode-eslint
