import fs from 'fs';
import path from 'path';
import { exit } from 'process';

(() => {
  console.log(process.argv);
  if (!process.argv[2] && !process.argv[3]) {
    console.error('Usage generateAwsExports.ts <graphqlEndpoint> <apiKey>');
    exit(1);
  }

  const filePath = path.join(__dirname, 'aws-exports.js');
  const fileName = path.parse(filePath).name;

  const data = `/* eslint-disable */
  // WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
  
  const awsmobile = {
    aws_project_region: 'us-east-1',
    aws_appsync_graphqlEndpoint: '${process.argv[2]}',
    aws_appsync_region: 'us-east-1',
    aws_appsync_authenticationType: 'API_KEY',
    aws_appsync_apiKey: '${process.argv[3]}',
  };
  
  export default awsmobile;
  `;

  fs.writeFileSync(path.join(__dirname, '..', `${fileName}.js`), data);
})();
