/* eslint-disable react/prop-types */
/* eslint-disable @typescript-eslint/explicit-module-boundary-types */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState } from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { GLTF as GLTFThree } from 'three/examples/jsm/loaders/GLTFLoader';
import { ModelProps } from './Model';

export interface YProps extends ModelProps {
  group: React.MutableRefObject<THREE.Group>;
}

declare module 'three-stdlib' {
  export interface GLTF extends GLTFThree {
    nodes: Record<string, THREE.Mesh>;
    materials: Record<string, THREE.Material>;
  }
}

export default function Y({ hue, group, ...props }: YProps) {
  //const group = useRef()
  console.log('in Y comp');
  // @ts-ignore
  /* prettier-ignore */
  const { nodes } = useGLTF('https://glb-files.s3.us-east-1.amazonaws.com/Chrom1Right.glb?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEM%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJIMEYCIQClA9EY%2B%2FagcqLmF366iD4nvXnDFMqfEhA9GoKNNbrtIAIhAMcxwhBqON1EnLjOEBihzwum2MJ%2Bg9H1blddLTysPymvKu0CCIj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQARoMNTMzNDc4NTE3NTM2IgyPnQgJbkupBFSIJc8qwQK7fPjHlxEuL8v0HjEl%2FiThSwTGovVUjcLtfkNIRHDPaL%2BYr7QynMds90nm5sRR859RtEljPlaQVYDCHKAaNlgYm7UMY2NGKRmaUOC5BmJlBlDfw0122lbcEIjaqC7V8BFMeAWu2%2B7eV9HjcLKXMDnGfKT0bvBGttvhbSuAVxrYZJCmravztQ1QXDXQmWT7Zv3vJ6fvEtiOj3X58Zh0YikFZ3ekKl4DzOv1vkH9m33q%2BTcJZjcYtEoOCBUpamuyczUpdjDanjP8ARW7K1TyRvyiZS343FRFTLFB63sM6STfQ69PvC7%2BaMdI68LfpbDy0W1n3yCvd9LfgW8%2FlJg3v2I6xvOpT30Tw17pBWeLmKlmv%2BDy%2BPfvsqvsMC1R%2Bs087YiBYL3C7lvFbEujCgV%2BDuCzdomMRVzRx%2BEwRevpupeiPFkw6YGZkwY6sgKWLBNkdLXM9hfbkPRB7%2FhNh9ojXhUGJX7eMLRJzN7AHu3SfnueW8tuNEJ4JBzhqoO%2BhG0KthhZ3ebYmpzewFIB8mP1YjlZcwDYT9dxAj%2Fbx%2Bxcq5DLdCDgooRuntHxW0tXIALFqLFbb8n6MkYnpXVfNo7NbTl00URhANHE1pkpjoWbpm1DkxTB1w%2BMz95cTHXylRWWc%2FNLUuXPeaJ6Aq52ppsdhri1VhK3KgX3txnzhNudfinBmjXGLkp48vLMclnsx7%2FrjRpidmvkuEOkpgqkD%2BaRqRKfoP32Wcmw1T%2FjcXpWogaLCQfQvmaa%2F%2FoedLlUClAoF7b%2FY5JD0fIhdVKdVDEu4WZSg33tYutD0f3pfPt%2BrNMXEALtmqs2ZIFqBm%2FU71GtNpPVwubLS5CxIUF8O1I%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220425T064526Z&X-Amz-SignedHeaders=host&X-Amz-Expires=43200&X-Amz-Credential=ASIAXYNOMFMQCLWDSOPS%2F20220425%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=35ab2dd551d67bc30ab5eafccab46a366318bed7d3d654e40f535ec9dd63d8ab');
  const [hovered, hover] = useState(false);
  const col = hovered ? 'hotpink' : hue;
  const material = new THREE.MeshBasicMaterial({ color: col });

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      onPointerOver={() => hover(true)}
      onPointerOut={() => hover(false)}
    >
      <mesh geometry={nodes.Group36303.geometry} material={material} />
      <mesh geometry={nodes.Group44649.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_0.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_0.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_1.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_1.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_2.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_2.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_3.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_3.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_4.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_4.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_5.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_5.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_6.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_6.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_7.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_7.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_8.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_8.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_9.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_9.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_10.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_10.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_11.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_11.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_12.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_12.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_13.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_13.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_14.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_14.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_15.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_15.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_16.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_16.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_17.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_17.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_18.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_18.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_19.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_19.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_20.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_20.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_21.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_21.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_22.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_22.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_23.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_23.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_24.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_24.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_25.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_25.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_26.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_26.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_27.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_27.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_28.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_28.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_29.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_29.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_30.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_30.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_31.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_31.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_32.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_32.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_33.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_33.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_34.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_34.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_35.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_35.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_36.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_36.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_37.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_37.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_38.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_38.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_39.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_39.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_40.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_40.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_41.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_41.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_42.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_42.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_43.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_43.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_44.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_44.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_45.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_45.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_46.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_46.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_47.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_47.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_48.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_48.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_49.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_49.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_50.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_50.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_51.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_51.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_52.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_52.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_53.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_53.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_54.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_54.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_55.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_55.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_56.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_56.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_57.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_57.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_58.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_58.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_59.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_59.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_60.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_60.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_61.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_61.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_62.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_62.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_63.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_63.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_64.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_64.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_65.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_65.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_66.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_66.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_67.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_67.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_68.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_68.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_69.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_69.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_70.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_70.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_71.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_71.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_72.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_72.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_73.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_73.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_74.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_74.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_75.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_75.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_76.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_76.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_77.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_77.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_78.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_78.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_79.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_79.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_80.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_80.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_81.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_81.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_82.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_82.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_83.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_83.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_84.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_84.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_85.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_85.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_86.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_86.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_87.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_87.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_88.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_88.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_89.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_89.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_90.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_90.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_91.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_91.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_92.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_92.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_93.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_93.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_94.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_94.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_95.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_95.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_96.geometry} material={material} />
      <mesh geometry={nodes.Group44649_node_96.geometry} material={material} />
      <mesh geometry={nodes.Group36303_node_97.geometry} material={material} />
      <mesh geometry={nodes.Group65350.geometry} material={material} />
    </group>
  );
}

// useGLTF.preload('/Chrom1Right.glb');
